<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Id Requests</title>
    <Link rel="stylesheet" href="css/bootstrap.css" />
    <Link rel="stylesheet" href="mystyle.css" />
    <Link rel="stylesheet" href="css/fonts.css" />
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>    
</head>
<body>
    <div class="container">
        <div col-sm-6>
        <?php
        $postfix="";
        $prefix="";
        $id_generated="";
$conn=new mysqli("localhost","root","","saral_voting_db");
$id=$_GET['id'];
$select="select * from id_request_tbl where id='$id'";
$run=$conn->query($select);
if($run->num_rows>0){
    while($row=$run->fetch_array()){
        $user_email=$row['user_email'];
        $user_province=$row['user_province'];
    }
    //Switch statement use gareko
    switch ($user_province){
        case'Sudurpashchim';
        $prefix="supa";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Madhesh';
        $prefix="madh";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Bagmati';
        $prefix="bgmt";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Karnali';
        $prefix="krnl";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Gandaki';
        $prefix="gndk";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Lumbini';
        $prefix="lmbn";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        case'Province1';
        $prefix="pvn1";
        $rand=rand(9999999,1234567);
        $postfix="srlv";
        $id_generated=$prefix.$rand.$postfix;
        break;
        default;
        break;
    }
        ?>
                <form method="post">
            <div class="form-group">
<label for="exampleInputEmail">User Email</label>
 <input type="email" class="form-control" name="user_email" id="exampleInputEmail" placeholder="Enter email" required readonly value="<?php echo $user_email;?>">
</div>
<div class="form-group">
<label for="exampleInputEmail">User Province</label>
 <input type="text" class="form-control" name="user_province" id="exampleInputEmail" placeholder="Enter province" required readonly value="<?php echo $user_province;?>">
</div>
<div class="form-group">
<label for="exampleInputEmail">User Unique Id Generated By System</label>
 <input type="text" class="form-control" name="user_id_generated" id="exampleInputEmail" placeholder="Enter province" required readonly value="<?php echo strtoupper($id_generated);?>">
</div>
<div class="form-group">
    <input type="submit" name="Update" value="Update Unique User ID "class="form-control btn btn-success">

</div>
        </form>

        <?php
    

}
else{
    echo "Sorry! Record Not Found";
}
?>
        </div>
        <div class="col-sm-6">

        </div>

    </div>
</body>
</html>
<?php
if(isset($_POST['Update'])){
    $user_email=$_POST['user_email'];
    $user_id_generated=$_POST['user_id_generated'];
    $update="update users_db set user_id_generated='$user_id_generated'where user_email='$user_email'";
    $run=$conn->query($update);
    if($run){
        
        $delete="delete from id_request_tbl where user_email='$user_email'";
        $del=$conn->query($delete);
        if($del){
            echo "<script>alert('Unique ID Updated Successfully And Deleted...')</script>";
        echo"<script>window.location.href='idrequest.php' </script>";
        }
    }
    else{
        echo "<script>alert('Oops! Something Went Wrong Error!')</script>";
    }
}
?>